#!/bin/zsh

sxhkd &

ws1=desktop
ws2=browse
ws3=files
ws4=music
ws5=cli
ws6=code
ws7=android
ws8=gaming
ws9=9
ws0=0

bspc config border_width          2
bspc config window_gap            3
bspc config top_padding           30

bspc config split_ratio           0.52
bspc config single_monocle        true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config click_to_focus        true
bspc config adaptive_raise        true

xrandr --output DVI-D-0 --primary

bspc monitor DVI-D-0 -d $ws6 $ws7 $ws8 $ws9 $w0
bspc monitor HDMI-0 -d $ws1 $ws2 $ws3 $ws4 $ws5

#bspc desktop $ws2 -l monocle

bspc rule -a Firefox desktop=^2
bspc rule -a Chromium desktop=^2 floating=on follow=on
bspc rule -a Spotify desktop=^4
bspc rule -a Termite desktop=^1
bspc rule -a Steam desktop=^8
bspc rule -a nautilus desktop=^5
bspc rule -a Atom desktop=^6
bspc rule -a android-studio desktop=^7

compton -b &
udiskie -q &
feh --bg-center ~/Pictures/background.jpg
xss-lock -- i3lock -i ~/Pictures/lockscreen.png &
~/.config/polybar/launch.sh
xrdb ~/.Xresources
~/.bin/towerautostart.sh
