#!/bin/zsh

sxhkd &

ws1=home
ws2=browse
ws3=files
ws4=mail
ws5=code
ws6=android
ws7=music
ws8=vbox
ws9=empty1
ws0=empty2

bspc config border_width          2
bspc config window_gap            3
bspc config top_padding           32

bspc config split_ratio           0.52
bspc config single_monocle        true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config click_to_focus        true
bspc config adaptive_raise        true

bspc monitor -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws0

#bspc desktop $ws2 -l monocle

bspc rule -a Firefox desktop=^2
bspc rule -a Chromium desktop=^2 floating=on follow=on
bspc rule -a Thunderbird desktop=^4
bspc rule -a Termite desktop=^1
bspc rule -a Nautilus desktop=^3
bspc rule -a Atom desktop=^5
bspc rule -a android-studio desktop=^6
bspc rule -a Spotify desktop=^7
bspc rule -a VirtualBox state=floating desktop=^8
bspc rule -a Gedit state=floating
bspc rule -a Gimp state=floating follow=on desktop=^9

compton -b &
udiskie -q &
feh --bg-center ~/Pictures/flamedrinks.jpg
#xss-lock -- i3lock -i ~/Pictures/MiamiCityPurple.png -e &
xss-lock -- i3lock-fancy &
~/.config/polybar/launch.sh
xrdb ~/.Xresources
~/.bin/laptopautostart.sh
